# Generated by Django 3.2.5 on 2021-08-09 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_project_blog_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_blog',
            name='description',
            field=models.TextField(max_length=900),
        ),
    ]
